// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogviqmukhjqfbhczxkxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndmlxbXVraGpxZmJoY3p4a3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDc4MzIsImV4cCI6MjA2MzEyMzgzMn0.UK_XPeWm4X0u-jWeIMDnBoDn2UOp5B0VnqarRKO40L8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);